
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>

int r;

int f(int i, int n)
{
	return n + 10 * i * r * r; 
}

int main(int argc, char* argv[])
{
	if (argc < 2) { 
		fprintf(stderr, "Provide a parameter r > 0 for the size of the insertion system.\n");
		return EXIT_FAILURE;
	}

	r = atoi(argv[1]);
	if (r < 1 || r % 2 != 1) {
		fprintf(stderr, "Your r=%d is not positive and odd.\n", r);
		return EXIT_FAILURE;
	}

	int x = f(5, 0);

	printf("# Monomers generated by nondetermfastis.\n");
	printf("# Parameters:\n #r = %d\n #x = %d (dead symbol)\n\n", r, x);

	printf("# Initiator\n");
	printf("(%d, %d) (%d*, %d*)\n", f(0, 0), f(0, 0), f(0, 0), f(0, 0));


	printf("# -------- Inner Even-To-Odd --------\n\n");

	printf("# Step 1\n");
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; b += 2) {
			printf("(%d*, %d*, %d, %d)-\n", f(1, b+1), f(0, a), f(0, a), x);
			printf("(%d*, %d, %d, %d)+\n",  f(0, b),   x,       f(1, a), f(1, b+1));
			printf("(%d*, %d*, %d, %d)-\n", f(1, b+1), f(1, a), f(0, a), f(2, b+2));
		}
	}
	printf("\n");

	printf("# Step 2\n");
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; b += 2) {
			printf("(%d*, %d*, %d, %d)+\n", f(2, b+2), f(2, a), x,       f(1, b+1));
			printf("(%d*, %d*, %d, %d)-\n", f(0, b+2), f(0, a), f(2, a), x);
		}
	}
	printf("\n");

	printf("# Step 3\n");
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; b += 2) {
			printf("(%d*, %d, %d, %d)+\n", f(2, b+2), x,       f(3, a), f(0, b+2));
			printf("(%d, %d*, %d, %d)-\n", x,         f(3, a), f(0, a), f(0, b+2));
		}
	}
	printf("\n");

	printf("# -------- Inner Odd-To-Even Increment --------\n\n");

	printf("# Step 1\n");
	for (int a = 0; a <= r; ++a) {
		for (int b = 1; b < r; b += 2) {
			printf("(%d*, %d*, %d, %d)-\n", f(0, b+1), f(1, a), f(1, a), x);
			printf("(%d*, %d, %d, %d)+\n",  f(1, b),   x,       f(0, a), f(0, b+1));
			printf("(%d*, %d*, %d, %d)-\n", f(0, b+1), f(0, a), f(1, a), x);
		}
	}
	printf("\n");


	printf("# -------- Outer Increment --------\n\n");

	printf("# Step 1\n");
	for (int a = 0; a < r; ++a) {
		printf("(%d*, %d, %d, %d)+\n",  f(1, r), x,         f(3, a+1), f(1, r));
		printf("(%d*, %d*, %d, %d)-\n", f(0, 0), f(3, a+1), f(1, a),   x);
		printf("(%d*, %d, %d, %d)+\n",  f(1, r), x,         f(0, a+1), f(0, 0));
		printf("(%d*, %d*, %d, %d)-\n", f(0, 0), f(0, a+1), f(3, a+1), x);
	}
	printf("\n");

	return 0;
}

