
#include <iostream>

using std::cerr;
using std::cout;
using std::endl;

int r;

int f(int i, int n) {
	return n + 10 * i * r * r; 
}

int main(int argc, char* argv[]) {
	if (argc < 2) { 
		cerr << "Provide a parameter r > 0 for the size of the insertion system." << endl;
		return EXIT_FAILURE;
	}

	r = atoi(argv[1]);
	if (r < 1 || r % 2 != 1) {
		cerr << "Your r = " << r << " is not positive and odd." << endl;
		return EXIT_FAILURE;
	}

	int x = f(5, 0);

	cout << "# Monomers generated by nondetermfastis." << endl;
	cout << "# Parameters:" << endl << "#r = " << r << endl << "#x = " << x << " (dead symbol)" << endl << endl;
	cout << "# Initiator" << endl;
	cout << "(" << f(0, 0) << ", " << f(0, 0) << ") (" << f(0, 0) << "*, " << f(0, 0) << "*)" << endl;

	cout << "# -------- Inner Even-To-Odd --------" << endl << endl;

	cout << "# Step 1" << endl;
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; b += 2) {
			cout << "(" << f(1, b+1) << "*, " << f(0, a) << "*, " << f(0, a) << ", " << x << ")-" << endl;
			cout << "(" << f(0, b) << "*, " << x << ", " << f(1, a) << ", " << f(1, b+1) << ")+" << endl;
			cout << "(" << f(1, b+1) << "*, " << f(1, a) << "*, " << f(0, a) << ", " << f(2, b+2) << ")-" << endl;
		}
	}
	cout << endl;

	cout << "# Step 2" << endl;
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; b += 2) {
			cout << "(" << f(2, b+2) << "*, " << f(2, a) << "*, " << x << ", " << f(1, b+1) << ")+" << endl;
			cout << "(" << f(0, b+2) << "*, " << f(0, a) << "*, " << f(2, a) << ", " << x << ")-" << endl;
		}
	}
	cout << endl;

	cout << "# Step 3" << endl;
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; b += 2) {
			cout << "(" << f(2, b+2) << "*, " << x << ", " << f(3, a) << ", " << f(0, b+2) << ")+" << endl;
			cout << "(" << x << ", " << f(3, a) << "*, " << f(0, a) << ", " << f(0, b+2) << ")-" << endl;
		}
	}
	cout << endl;

	cout << "# -------- Inner Odd-To-Even Increment --------" << endl << endl;

	cout << "# Step 1" << endl;
	for (int a = 0; a <= r; ++a) {
		for (int b = 1; b < r; b += 2) {
			cout << "(" << f(0, b+1) << "*, " << f(1, a) << "*, " << f(1, a) << ", " << x << ")-" << endl;
			cout << "(" << f(1, b) << "*, " << x << ", " << f(0, a) << ", " << f(0, b+1) << ")+" << endl;
			cout << "(" << f(0, b+1) << "*, " << f(0, a) << "*, " << f(1, a) << ", " << x << ")-" << endl;
		}
	}
	cout << endl;


	cout << "# -------- Outer Increment --------" << endl << endl;

	cout << "# Step 1" << endl;
	for (int a = 0; a < r; ++a) {
		cout << "(" << f(1, r) << "*, " << x << ", " << f(3, a+1) << ", " << f(1, r) << ")+" << endl;
		cout << "(" << f(0, 0) << "*, " << f(3, a+1) << "*, " << f(1, a) << ", " << x << ")-" << endl;
		cout << "(" << f(1, r) << "*, " << x << ", " << f(0, a+1) << ", " << f(0, 0) << ")+" << endl;
		cout << "(" << f(0, 0) << "*, " << f(0, a+1) << "*, " << f(3, a+1) << ", " << x << ")-" << endl;
	}
	cout << endl;

	return 0;
}

