
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>

int r;

int f(int i, int n)
{
	return n + 2 * i * r * r; 
}

int main(int argc, char* argv[])
{
	if (argc < 2) { 
		fprintf(stderr, "Provide a parameter r > 0 for the size of the insertion system.\n");
		return EXIT_FAILURE;
	}

	r = atoi(argv[1]);
	if (r < 1) {
		fprintf(stderr, "Your r=%d is not positive.\n", r);
		return EXIT_FAILURE;
	}

	int x = f(18, 0);

	printf("# Monomers generated by superfastgrowingis.\n");
	printf("# Parameters:\n#r = %d\n#x = %d (dead symbol)\n\n", r, x);

	printf("# Initiator\n");
	printf("(0, 0)(0, 0*)\n\n");	


	printf("# -------- Positive monomers --------\n\n");


	printf("# Middle - Step 1\n");
	for (int c = 0; c < r; ++c) {
		printf("(%d*, %d, %d, %d*)+\n", r, f(2, c), x, c);
	}
	printf("\n");

	printf("# Middle - Step 2\n");
	for (int c = 0; c < r; ++c) {
		printf("(%d*, %d, %d, %d*)+\n", r, x, f(3, c), f(1, c));
	}
	printf("\n");
	
	printf("# Middle - Step 3\n");
	for (int c = 0; c < r; ++c) {
		printf("(%d*, %d, %d, %d*)+\n", 0, f(4, c+1), x, f(1, c));
	}
	printf("\n");


	printf("# Outer - Step 1\n");
	printf("(%d*, %d, %d, %d*)+\n", r, x, f(5, r), r);
	printf("\n");

	printf("# Outer - Step 2\n");
	for (int a = 0; a < r; ++a) {
		printf("(%d, %d*, %d, %d*)+\n", f(6, a), a+1, x, r);
	}
	printf("\n");

	printf("# Outer - Step 3\n");
	for (int a = 0; a < r; ++a) {
		printf("(%d*, %d, %d, %d*)+\n", f(7, r), x, f(8, r), f(6, a));
	}
	printf("\n");

	printf("# Outer - Step 4\n");
	for (int a = 0; a < r; ++a) {
		printf("(%d*, %d, %d, %d*)+\n", 0, f(9, a), x, f(6, a));
	}
	printf("\n");


	printf("# Inner - Step 1\n");
	for (int b = 0; b < r; ++b) {
		for (int c = 0; c <= r; ++c) {
				printf("(%d*, %d, %d, %d*)+\n", b, f(9, c), f(9, b+1), c);
		}	
	}
	printf("\n");

	printf("# Inner - Step 2\n");
	printf("# (None)\n\n");

	printf("# Inner - Step 3\n");
	for (int b = 0; b < r; ++b) {
		for (int c = 0; c <= r; ++c) {
				printf("(%d*, %d, %d, %d*)+\n", b, x, f(12, b), f(10, c));
		}	
	}
	printf("\n");

	printf("# Inner - Step 4\n");
	for (int b = 0; b < r; ++b) {
		for (int c = 0; c <= r; ++c) {
				printf("(%d*, %d, %d, %d*)+\n", f(11, b), f(13, c), x, f(10, c));
		}	
	}
	printf("\n");

	printf("# Inner - Step 5\n");
	for (int b = 0; b < r; ++b) {
		for (int c = 0; c <= r; ++c) {
				printf("(%d*, %d, %d, %d*)+\n", f(11, b), x, f(14, b+1), c);
		}	
	}
	printf("\n");


			
	printf("# -------- Negative monomers --------\n\n");


	printf("# Middle - Step 1\n");
	for (int a = 0; a <= r; ++a) {
		for (int c = 0; c < r; ++c) {
			printf("(%d, %d*, %d*, %d)-\n", f(1, c), a, f(2, c), x);
		}	
	}
	printf("\n");

	printf("# Middle - Step 2\n");
	for (int a = 0; a <= r; ++a) {
		for (int c = 0; c < r; ++c) {
			printf("(%d, %d*, %d, %d)-\n", x, f(3, c), a, 0);
		}
	}
	printf("\n");

	printf("# Middle - Step 3\n");
	for (int a = 0; a <= r; ++a) {
		for (int c = 0; c < r; ++c) {
			printf("(%d, %d*, %d*, %d)-\n", c+1, a, f(4, c+1), x);
		}	
	}
	printf("\n");


	printf("# Outer - Step 1\n");
	for (int a = 0; a < r; ++a) {
		printf("(%d, %d*, %d, %d*)-\n", x, f(5, r), a, f(6, a));
	}
	printf("\n");	

	printf("# Outer - Step 2\n");
	for (int a = 0; a < r; ++a) {
		printf("(%d, %d*, %d, %d)-\n", x, a, a+1, f(7, r));
	}
	printf("\n");	

	printf("# Outer - Step 3\n");
	for (int a = 0; a < r; ++a) {
		printf("(%d, %d*, %d, %d)-\n", x, f(8, r), a+1, 0);
	}
	printf("\n");

	printf("# Outer - Step 4\n");
	for (int a = 0; a < r; ++a) {
		printf("(%d, %d*, %d*, %d)-\n", 0, a+1, f(9, a), x);
	}
	printf("\n");


	printf("# Inner - Step 1\n");
	printf("# (None)\n\n");

	printf("# Inner - Step 2\n");
	for (int a = 0; a <= r; ++a) {
		for (int c = 0; c <= r; ++c) {
			printf("(%d, %d*, %d*, %d)-\n", f(10, c), a, f(9, c), x);
		}	
	}
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; ++b) {
			printf("(%d, %d*, %d, %d)-\n", x, f(9, b+1), a, b+1);
		}	
	}
	printf("\n");

	printf("# Inner - Step 3\n");
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; ++b) {
			printf("(%d, %d*, %d, %d)-\n", x, f(12, b), a, f(11, b));
		}	
	}
	printf("\n");

	printf("# Inner - Step 4\n");
	for (int a = 0; a <= r; ++a) {
		for (int c = 0; c <= r; ++c) {
			printf("(%d, %d*, %d*, %d)-\n", c, a, f(13, c), x);
		}	
	}
	printf("\n");

	printf("# Inner - Step 5\n");
	for (int a = 0; a <= r; ++a) {
		for (int b = 0; b < r; ++b) {
			printf("(%d, %d*, %d, %d)-\n", x, f(14, b+1), a, b+1);
		}	
	}
	printf("\n");

	return EXIT_SUCCESS;
}

